//! SQLite-backed document and edit projection storage.

use std::path::Path;

use rusqlite::{Connection, OptionalExtension, params, types::Type};
use sim_lib_doc_core::{Doc, DocId, Edit};

use crate::codec::{CodecError, decode_doc, decode_edit, encode_doc, encode_edit};

/// SQLite document store used as a local read projection.
pub struct DocStore {
    conn: Connection,
}

impl DocStore {
    /// Opens or creates a document store at `path` and applies the schema.
    pub fn create(path: &Path) -> rusqlite::Result<Self> {
        let conn = Connection::open(path)?;
        conn.execute_batch(include_str!("schema.sql"))?;
        Ok(Self { conn })
    }

    /// Saves a document snapshot.
    ///
    /// The document body must expose a pure kernel datum snapshot. Opaque live
    /// objects are rejected instead of being flattened into unstable text.
    pub fn save_doc(&self, doc: &Doc) -> rusqlite::Result<()> {
        let encoded = encode_doc(doc).map_err(sql_encode_error)?;
        self.conn.execute(
            "INSERT INTO docs (id, kind, body) VALUES (?1, ?2, ?3)
             ON CONFLICT(id) DO UPDATE SET kind = excluded.kind, body = excluded.body",
            params![doc.id.as_str(), doc.kind.as_str(), encoded],
        )?;
        Ok(())
    }

    /// Loads a document snapshot by id.
    pub fn load_doc(&self, id: &DocId) -> rusqlite::Result<Option<Doc>> {
        self.conn
            .query_row(
                "SELECT body FROM docs WHERE id = ?1",
                params![id.as_str()],
                |row| {
                    let encoded: String = row.get(0)?;
                    decode_doc(&encoded).map_err(|error| sql_decode_error(0, error))
                },
            )
            .optional()
    }

    /// Records that a kernel ledger sequence projected an edit into this store.
    ///
    /// The `seq` column stores the supplied ledger sequence directly. It is not
    /// generated by SQLite, so duplicate or out-of-range sequences fail instead
    /// of silently creating a private counter.
    pub fn project_commit(
        &self,
        doc: &DocId,
        edit: &Edit,
        ledger_seq: u64,
    ) -> rusqlite::Result<u64> {
        if &edit.doc != doc {
            return Err(sql_encode_error(CodecError::new(format!(
                "edit targets {}, not {}",
                edit.doc.as_str(),
                doc.as_str()
            ))));
        }
        let seq = sqlite_seq(ledger_seq)?;
        let encoded = encode_edit(edit).map_err(sql_encode_error)?;
        let inverse = encode_edit(&edit.inverted()).map_err(sql_encode_error)?;
        self.conn.execute(
            "INSERT INTO edit_projection (seq, doc, edit, inverse) VALUES (?1, ?2, ?3, ?4)",
            params![seq, doc.as_str(), encoded, inverse],
        )?;
        Ok(ledger_seq)
    }

    /// Returns the inverse edit for the latest projected ledger sequence.
    ///
    /// This method does not rewrite the saved document or delete projection
    /// rows. It reports the edit a caller can submit back to the authoritative
    /// ledger.
    pub fn undo_last(&self, doc: &DocId) -> rusqlite::Result<Option<Edit>> {
        self.conn
            .query_row(
                "SELECT inverse FROM edit_projection WHERE doc = ?1 ORDER BY seq DESC LIMIT 1",
                params![doc.as_str()],
                |row| {
                    let encoded: String = row.get(0)?;
                    decode_edit(&encoded).map_err(|error| sql_decode_error(0, error))
                },
            )
            .optional()
    }
}

fn sqlite_seq(seq: u64) -> rusqlite::Result<i64> {
    i64::try_from(seq).map_err(|_| {
        sql_encode_error(CodecError::new(format!(
            "ledger sequence {seq} does not fit sqlite INTEGER"
        )))
    })
}

fn sql_encode_error(error: CodecError) -> rusqlite::Error {
    rusqlite::Error::ToSqlConversionFailure(Box::new(error))
}

fn sql_decode_error(index: usize, error: CodecError) -> rusqlite::Error {
    rusqlite::Error::FromSqlConversionFailure(index, Type::Text, Box::new(error))
}
