//! Local file generation for annual accounts packs.

use sim_codec_ooxml::{
    PPTX_CODEC_ID, PPTX_EXTENSION, PptxCodec, XLSX_CODEC_ID, XLSX_EXTENSION, XlsxCodec,
};
use sim_kernel::Cx;
use sim_lib_deck::deck_to_doc;
use sim_lib_doc_core::{DocCodec, DocCodecOptions, DocId};
use sim_lib_doc_ledger::project_statements;
use sim_lib_sheet::sheet_to_doc;

use crate::{AnnualAccountsPack, PackError, pack::validate_pack};

/// One generated office file.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Stable output kind such as `spreadsheet` or `deck`.
    pub kind: String,
    /// Suggested file name.
    pub filename: String,
    /// Codec that generated the bytes.
    pub codec_id: String,
    /// File extension generated by the codec.
    pub extension: String,
    /// Encoded file bytes.
    pub bytes: Vec<u8>,
}

impl GeneratedFile {
    fn new(
        kind: impl Into<String>,
        filename: impl Into<String>,
        codec_id: &'static str,
        extension: &'static str,
        bytes: Vec<u8>,
    ) -> Self {
        Self {
            kind: kind.into(),
            filename: filename.into(),
            codec_id: codec_id.to_owned(),
            extension: extension.to_owned(),
            bytes,
        }
    }
}

/// Encoded spreadsheet and presentation files for one statement set.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EncodedStatementFiles {
    /// Spreadsheet generated from the statement sheet projection.
    pub spreadsheet: GeneratedFile,
    /// Presentation generated from the statement deck projection.
    pub deck: GeneratedFile,
}

/// Generates local `.xlsx` and `.pptx` bytes through the office OOXML codecs.
pub fn encode_statement_files(
    cx: &mut Cx,
    pack: &AnnualAccountsPack,
) -> Result<EncodedStatementFiles, PackError> {
    validate_pack(pack)?;
    let projection = project_statements(cx, &pack.statements)?;
    let options = DocCodecOptions::new(cx.factory().nil()?);
    let sheet_doc = sheet_to_doc(
        cx,
        DocId::new(format!("annual-accounts/{}/statements-sheet", pack.year)),
        &projection.sheet,
    )
    .map_err(PackError::from_display)?;
    let deck_doc = deck_to_doc(
        cx,
        DocId::new(format!("annual-accounts/{}/statements-deck", pack.year)),
        &projection.deck,
    )
    .map_err(PackError::from_display)?;
    let (spreadsheet_bytes, _) = XlsxCodec.encode(cx, &sheet_doc, &options)?;
    let (deck_bytes, _) = PptxCodec.encode(cx, &deck_doc, &options)?;

    Ok(EncodedStatementFiles {
        spreadsheet: GeneratedFile::new(
            "spreadsheet",
            format!("annual-accounts-{}{}", pack.year, XLSX_EXTENSION),
            XLSX_CODEC_ID,
            XLSX_EXTENSION,
            spreadsheet_bytes,
        ),
        deck: GeneratedFile::new(
            "deck",
            format!("annual-accounts-{}{}", pack.year, PPTX_EXTENSION),
            PPTX_CODEC_ID,
            PPTX_EXTENSION,
            deck_bytes,
        ),
    })
}
